web:
    #image: nginx:latest
    build: .
    container_name: nginx
    ports:
        - "8080:8080"
    volumes:
        - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        - ./:/code
        - ./logs/:/var/log/nginx/
    links:
        - php
php:
    image: php:7-fpm
    container_name: php
    volumes:
        - ./:/code

