web:
    image: nginx:latest
    ports:
        - "8080:8080"
    volumes:
        - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
        - ./:/code
        - ./logs/:/var/log/nginx/
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./:/code